import assert from 'node:assert/strict';
import fs from 'node:fs';
import {parseCSV,parseMaestro,mergeMaestro,packLines,unpackLines} from '../src/buyer.mjs';
import {cleanExport,buildShared} from '../src/ventas-compartidas.mjs';
import {createHandler,encode,decode} from '../neon/buyer/handler.mjs';
import {connection,applySchema} from './neon-sql.mjs';

const maestro='SKU,Nombre,Categorías,Familia,Buyer Persona\r\nA,"Soporte, TV",,Fijos,Juan\r\nB,Mopa,,Limpieza,Mariana';
assert.deepEqual(parseMaestro('\uFEFF'+maestro),parseMaestro(mergeMaestro('',maestro)));
assert.equal(parseCSV('a;b\n"doble ""quote""; dentro";"otra\nlínea"',';')[1][1],'otra\nlínea');
assert.throws(()=>parseMaestro('SKU,Nombre\nA,Nombre'));
assert.throws(()=>parseMaestro('SKU,Buyer Persona\nA,Juan,Extra'));
const userCsv='/Users/agustin/Downloads/maestro-naku-NUEVA.csv';
if(fs.existsSync(userCsv))assert.equal(parseMaestro(fs.readFileSync(userCsv,'utf8')).length,268);
const mh=['# de venta','Fecha de venta','Estado','Descripción del estado','Unidades','SKU','Ingresos por productos (ARS)','Cargo por venta e impuestos (ARS)','Total (ARS)','Precio unitario de venta de la publicación (ARS)','Título de la publicación'];
const th=['Número de orden','Fecha','Estado de la orden','Estado del pago','SKU','Precio del producto','Cantidad del producto','Subtotal de productos','Descuento','Costo de envío','Total','Costo de procesamiento','Interés por cuotas','Impuestos','Total neto','Nombre del producto','Medio de envío','Provincia o estado','Reembolso'];
const tn=id=>cleanExport('tn',[th,[id,'01/08/2026','Archivada','Recibido','A',100,1,300,0,40,340,10,0,0,330,'Soporte','Correo','Buenos Aires',0],['','','','','B',100,2,'','','','','','','','','Mopa','','','']],'tn.csv');
const ml=cleanExport('ml',[mh,['10','31 de agosto de 2026','Paquete de 2 productos','','','',300,-30,265,'',''],['11','31 de agosto de 2026','Entregado','',1,'A','','','',100,'Soporte'],['12','31 de agosto de 2026','Entregado','',2,'B','','','',100,'Mopa']],'ml.xlsx');
const empty={ventas:packLines([]),maestro,manifest:[]};
const support={costos:{pares:[['A',10],['B',20]],mes:'2026-07',hoja:'JULIO 2026',archivo:'costos.xlsx'},orders:[],schemas:[]};
let result=buildShared(empty,support,{exports:[tn('1'),ml]},null);
assert.equal(result.finance.vistas.todos['mes:2026-08'].eerr.ordenes,2);
assert.equal(result.finance.vistas.todos['mes:2026-08'].eerr.unidades,6);
assert.equal(unpackLines(result.buyer.ventas).filter(l=>l.canal==='TiendaNube').length,2);
assert.ok(unpackLines(result.buyer.ventas).every(l=>l.mes==='2026-08'));
const duplicated=buildShared(result.buyer,result.sources,{exports:[tn('1'),ml]},result.finance);
assert.equal(duplicated.finance.vistas.todos['mes:2026-08'].eerr.ordenes,2);
assert.equal(duplicated.buyer.ventas.rows.length,result.buyer.ventas.rows.length);
const changed=tn('1');changed.rows[0][2]='Cancelada';
const updated=buildShared(result.buyer,result.sources,{exports:[changed]},result.finance);
assert.equal(updated.finance.vistas.todos['mes:2026-08'].eerr.ordenes,1);
assert.ok(unpackLines(updated.buyer.ventas).filter(l=>l.canal==='TiendaNube').every(l=>!l.billable));
const mapped=buildShared(result.buyer,result.sources,{maestro:'SKU;Buyer Persona\nA;Mario'},result.finance);
assert.ok(unpackLines(mapped.buyer.ventas).filter(l=>l.sku==='A').every(l=>l.buyer==='Mario'));
assert.equal(mapped.result.cambios,2);
assert.equal(parseMaestro(mapped.buyer.maestro).length,3);
console.log('✓ CSV, paquetes ML, productos TN, superposición, cancelaciones y maestro parcial');

if(process.env.NAKU_TEST_BRANCH){
  assert.notEqual(process.env.NAKU_TEST_BRANCH,'br-wispy-lake-ayf0dl28','No ejecutar pruebas en producción');
  const sql=connection(process.env.NAKU_TEST_BRANCH);
  await applySchema(sql,fs.readFileSync('neon/buyer/esquema.sql','utf8'));
  await sql("update naku_clave set hash=encode(sha256('test-finance-only'::bytea),'hex') where id=1");
  await sql("insert into buyer_clave values(1,encode(sha256('test-buyer-only'::bytea),'hex')) on conflict(id) do update set hash=excluded.hash");
  await sql('delete from buyer_historial');await sql('delete from buyer_estado');
  await sql('insert into buyer_estado(id,revision,datos,fuentes) values(1,1,$1,$2)',[encode(empty),encode(support)]);
  const handler=createHandler(sql);
  const call=async(path,op,key='test-buyer-only')=>{
    const r=await handler(new Request('https://test'+path,{method:op?'PUT':'GET',headers:{'x-naku-clave':key},...(op?{body:JSON.stringify({datos:encode(op)})}:{})}));
    return {status:r.status,data:await r.json()};
  };
  assert.equal((await call('/',null,'wrong')).status,401);
  assert.equal((await call('/finanzas',{id:'forbidden',exports:[tn('1')]})).status,403);
  let r=await call('/',{id:'first',exports:[tn('1'),ml]});assert.equal(r.status,200,JSON.stringify(r.data));
  assert.equal(r.data.revision,2);
  assert.ok(!r.data.fuentes&&!r.data.finance&&!decode(r.data.datos).costos);
  const duplicate=await call('/',{id:'first',exports:[tn('1'),ml]});assert.equal(duplicate.data.revision,2);
  const before=await call('/estado');
  const preview=await call('/preview',{id:'preview',exports:[tn('2')]},'test-finance-only');assert.equal(preview.status,200);
  assert.equal((await call('/estado')).data.revision,before.data.revision);
  const concurrent=await Promise.all([call('/',{id:'a',exports:[tn('2')]}),call('/finanzas',{id:'b',exports:[tn('3')]},'test-finance-only')]);
  assert.ok(concurrent.every(r=>r.status===200),JSON.stringify(concurrent.map(r=>({status:r.status,error:r.data.error}))));
  const saved=await call('/');const lines=unpackLines(decode(saved.data.datos).ventas);
  for(const order of ['1','2','3'])assert.ok(lines.some(l=>l.order_id===order));
  const finance=(await sql("select datos from tablero where id='direccion'")).rows[0].datos;
  assert.equal(finance.vistas.todos['mes:2026-08'].eerr.ordenes,4);
  assert.equal((await call('/',{id:'old-map',ventas:packLines([]),maestro:'SKU;Buyer Persona\nA;Mario',maestroRevision:1})).status,409);
  const rev=saved.data.revision;
  const fdate=(await sql("select actualizado from tablero where id='direccion'")).rows[0].actualizado;
  await assert.rejects(sql('select buyer_guardar($1,$2,$3,$4,$5::jsonb,$6::timestamptz)',['test-buyer-only',rev,encode(empty),encode(support),'{}',fdate]));
  assert.equal((await call('/estado')).data.revision,rev);
  console.log('✓ Neon aislado: permisos, vista previa, reintentos, dos cargas concurrentes, conflictos y rollback atómico');
}
